services:
  CoreBundle\EventListener\ExceptionListener:
    class: 'CoreBundle\EventListener\ExceptionListener'
    arguments:
      $exceptionResponseBuilder: '@CoreBundle\Services\HttpFoundation\ExceptionResponseBuilderInterface'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  CoreBundle\Services\HttpFoundation\ExceptionResponseBuilderInterface:
    class: 'CoreBundle\Services\HttpFoundation\ExceptionResponseBuilder'
    arguments:
      $logger: '@logger'
      $env: '%kernel.environment%'

  CoreBundle\EventListener\PermissionResponseListener:
    arguments:
      $authorizationChecker: '@security.authorization_checker'
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 101 }