services:
  CoreBundle\EventListener\ExceptionListener:
    class: 'CoreBundle\EventListener\ExceptionListener'
    arguments:
      $logger: '@logger'
      $env: '%kernel.environment%'
    tags:
    - { name: kernel.event_listener, event: kernel.exception }

