services:
  CoreBundle\Listener\ExceptionListener:
    class: 'CoreBundle\Listener\ExceptionListener'
    arguments:
      $logger: '@logger'
    tags:
    - { name: kernel.event_listener, event: kernel.exception }

  CoreBundle\Listener\AuthenticationListener:
    class: 'CoreBundle\Listener\AuthenticationListener'
    arguments:
      $loginManager: '@fos_user.security.login_manager'
      $firewallName: '%fos_user.firewall_name%'
    tags:
    - { name: kernel.event_listener, event: kernel.event_subscriber }

