# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  view:
    view_response_listener: 'force'
    formats:
      json: true
    mime_types:
      json: ['application/json']
  access_denied_listener:
    json: true
  routing_loader:
    default_format: json
    include_format: false
  format_listener:
    rules:
    - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: true }
  exception:
    codes:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
      'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
    messages:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': true