jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\App"
                path: "@App/Resources/config/serializer/fos"
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'