imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        handler_id:  ~
        storage_id: session.storage.mock_file
        name: MOCKSESSION
    profiler:
        collect: false

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     "%kernel.cache_dir%/test.db"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test:
    cache_db:
        sqlite: liip_functional_test.services_database_backup.sqlite

security:
    firewalls:
        main:
            http_basic: ~