mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /security

core:
    resource: "@CoreBundle/Resources/config/routing.yml"

users:
    type:     rest
    resource: CoreBundle\Controller\LoadingController