security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            encode_as_base64:     true
            iterations:           1000
            key_length:           40

    role_hierarchy:
        ROLE_MEMBER:  ROLE_TRIAL
        ROLE_OFFICER: ROLE_MEMBER
        ROLE_ADMIN:   ROLE_OFFICER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            logout_on_user_change: true
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                failure_handler: security.custom.authentication.failure
                success_handler: security.custom.authentication.success
            logout:
                path:   /security/logout
                target: /
                success_handler: security.custom.authentication.logout
            anonymous: true
            remember_me:
                secret:   "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        - { path: ^/event, role: ROLE_TRIAL }
        - { path: ^security/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^security/registration/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
