services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    CoreBundle\:
        resource: '../../src/CoreBundle/*'
        exclude: '../../src/CoreBundle/{Entity,Repository,Tests}'

    UserBundle\:
        resource: '../../src/UserBundle/*'
        exclude: '../../src/UserBundle/{Entity,Repository,Tests}'

    CoreBundle\Controller\:
        resource: '../../src/CoreBundle/Controller'
        tags: ['controller.service_arguments']
        public: true
