services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CoreBundle\Tests\:
        resource: '../../src/CoreBundle/Tests'

    UserBundle\Tests\:
        resource: '../../src/UserBundle/Tests'