services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CoreBundle\:
        resource: '../../src/CoreBundle/*'
        exclude: '../../src/CoreBundle/{Entity,Repository,Tests}'

    UserBundle\:
        resource: '../../src/UserBundle/*'
        exclude: '../../src/UserBundle/{Entity,Repository,Tests}'

    CoreBundle\Controller\:
        resource: '../../src/CoreBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
