fos_user_change_password:
    path:     /profile/password
    defaults: { _controller: UserBundle:ChangePassword:changePassword }
    methods:  [POST]

#fos_user_profile:
#    resource: "base/profile.xml"
#    prefix: /profile

fos_user_registration:
    resource: "base/registration.xml"
    prefix: /registration

#fos_user_resetting:
#    resource: "base/resetting.xml"
#    prefix: /resetting

fos_user_security:
    resource: "base/security.xml"