fos_user_change_password:
    path:     /profile/password
    defaults: { _controller: App:ChangePassword:changePassword }
    methods:  [POST]

#fos_user_profile:
#    resource: "base/profile.xml"
#    prefix: /profile

fos_user_registration:
    resource: "base/registration.xml"
    prefix: /registration

#fos_user_resetting:
#    resource: "base/resetting.xml"
#    prefix: /resetting

fos_user_security:
    resource: "base/security.xml"

user_role_promote:
    path:   /users/{userId}/promote/{role}
    defaults: { _controller: App:AccessControl:promote }
    methods: [POST]
    requirements:
      userId: \d+
      role: \w+

user_role_demote:
    path:   /users/{userId}/demote/{role}
    defaults: { _controller: App:AccessControl:demote }
    methods: [POST]
    requirements:
      userId: \d+
      role: \w+