#fos_user_change_password:
#    resource: "base/change_password.xml"
#    prefix: /profile

#fos_user_profile:
#    resource: "base/profile.xml"
#    prefix: /profile

fos_user_registration:
    resource: "base/registration.xml"
    prefix: /registration

#fos_user_resetting:
#    resource: "base/resetting.xml"
#    prefix: /resetting

fos_user_security:
    resource: "base/security.xml"