services:
  UserBundle\Controller\ChangePasswordController:
    class: 'UserBundle\Controller\ChangePasswordController'
    arguments:
      $eventDispatcher: '@event_dispatcher'
      $formFactory: '@fos_user.change_password.form.factory'
      $userManager: '@fos_user.user_manager'
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: ['controller.service_arguments']
    public: true

  UserBundle\Controller\AccessControlController:
    class: 'UserBundle\Controller\AccessControlController'
    arguments:
      $userManager: '@UserBundle\Manager\UserManagerInterface'
      $eventDispatcher: '@event_dispatcher'
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags: ['controller.service_arguments']
    public: true

  UserBundle\Handler\Security\AuthenticationFailure:
    class: 'UserBundle\Handler\Security\AuthenticationFailure'
    arguments:
      $exceptionResponseBuilder: '@CoreBundle\Services\HttpFoundation\ExceptionResponseBuilderInterface'

  UserBundle\Handler\Security\AuthenticationSuccess:
    class: 'UserBundle\Handler\Security\AuthenticationSuccess'
    arguments:
      $logger: '@logger'
      $router: '@router'
#      $loginRedirect: 'loadingcore_loading'
      $loginRedirect: '%vs_user_bundle.login_redirect%'
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

  UserBundle\Handler\Security\LogoutSuccess:
    class: 'UserBundle\Handler\Security\LogoutSuccess'


  security.custom.authentication.failure:
    alias: 'UserBundle\Handler\Security\AuthenticationFailure'

  security.custom.authentication.success:
    alias: 'UserBundle\Handler\Security\AuthenticationSuccess'

  security.custom.authentication.logout:
    alias: 'UserBundle\Handler\Security\LogoutSuccess'
